import { useCallback, useEffect, useState } from "react";
import { aiChat, aiRelated, aiSummarize, aiTags, aiExtractTodos, aiClassify, fetchAIStatus, fetchBacklinks, fetchGraph, fetchHealth, fetchLinks, fetchLocalGraph, fetchTagGraph, fetchVaultFiles, fetchVaultFile, patchVaultFile, searchNotes, listHistory, getHistory, createJob, acceptJob, rejectJob, undoHistory } from "./api/client";
import type { AIStatusResponse } from "./api/types";
import { StatusCard } from "./components/StatusCard";
import { Ribbon } from "./components/Ribbon";
import type { RibbonTool } from "./components/Ribbon";
import { SearchPanel } from "./components/SearchPanel";
import { GraphPanel } from "./components/GraphPanel";
import { AIPanel } from "./components/AIPanel";
import { WorkspaceShell } from "./components/WorkspaceShell";
import { AIHistoryPanel } from "./components/AIHistoryPanel";
import { SchedulerStatus } from "./components/SchedulerStatus";
import { configureWorkspaceApi, useWorkspaceStore } from "@localnote/workspace";
type ServerState="checking"|"connected"|"disconnected";
const AI_LABEL="Qwen3.5-4B";
function aiDisplayText(ai:AIStatusResponse|null,failed:boolean){if(failed||!ai)return `${AI_LABEL} / Unavailable`;if(ai.status==="not_configured")return `${AI_LABEL} / Not configured`;if(ai.status==="offline")return `${AI_LABEL} / Offline`;return ai.qwen_model?`${AI_LABEL} / Connected`:`${AI_LABEL} / Not detected`}
function aiDetail(ai:AIStatusResponse|null){return ai?.qwen_model?`Discovered ${ai.qwen_model}`:ai?.message??null}
export default function App(){const[server,setServer]=useState<ServerState>("checking");const[ai,setAi]=useState<AIStatusResponse|null>(null);const[aiFailed,setAiFailed]=useState(false);const[tool,setTool]=useState<RibbonTool>("files");const vaultStatus=useWorkspaceStore((s)=>s.tree.status);const openFile=useWorkspaceStore((s)=>s.openFile);const refresh=useCallback(async()=>{setServer("checking");setAiFailed(false);const[health,aiResult]=await Promise.allSettled([fetchHealth(),fetchAIStatus()]);setServer(health.status==="fulfilled"?"connected":"disconnected");if(aiResult.status==="fulfilled")setAi(aiResult.value);else{setAi(null);setAiFailed(true)}},[]);useEffect(()=>{configureWorkspaceApi({fetchVaultFiles,fetchVaultFile,patchVaultFile,fetchLinks,fetchBacklinks,searchNotes,fetchGraph,fetchLocalGraph,fetchTagGraph,aiChat,aiSummarize,aiTags,aiRelated,aiExtractTodos,aiClassify,listHistory,getHistory,createJob,acceptJob,rejectJob,undoHistory});void refresh()},[refresh]);const openFromSearch=(path:string)=>{void openFile(path);setTool("files")};const openFromGraph=(path:string)=>{void openFile(path);setTool("files")};const openSchedulerPreview=useCallback((jobId:string)=>{void useWorkspaceStore.getState().selectHistory(jobId);setTool("history")},[]);return <><header className="app-header"><div><h1>LocalNote Server</h1><p>Markdown-first local workspace</p></div><Ribbon activeTool={tool} onSelect={setTool}/></header>{tool==="search"&&<SearchPanel onOpen={openFromSearch} onClose={()=>setTool("files")}/>}{tool==="graph"&&<GraphPanel onOpenNote={openFromGraph} onClose={()=>setTool("files")}/>}
{tool==="ai"&&<AIPanel onClose={()=>setTool("files")} onOpenNote={(path)=>{void openFile(path);setTool("files")}}/>}{(tool as string)==="history"&&<AIHistoryPanel onClose={()=>setTool("files")}/>}<section className="status-cards"><StatusCard label="Server" value={`Server: ${server==="connected"?"Connected":server==="disconnected"?"Disconnected":"Checking…"}`} tone={server==="connected"?"ok":server==="disconnected"?"bad":"info"}/><StatusCard label="Vault" value={`Vault: ${vaultStatus==="idle"||vaultStatus==="not_configured"?"Not configured":vaultStatus==="ready"?"Connected":vaultStatus==="unavailable"?"Unavailable":vaultStatus==="error"?"Error":"Checking…"}`} tone={vaultStatus==="ready"?"ok":vaultStatus==="error"?"bad":vaultStatus==="unavailable"?"warn":"info"} detail="Files are loaded through the local Vault REST API"/><StatusCard label="AI" value={`AI: ${aiDisplayText(ai,aiFailed)}`} tone={aiFailed||ai?.status==="offline"?"warn":ai?.status==="connected"?"ok":"info"} detail={aiDetail(ai)}/><SchedulerStatus active={server==="connected"} onPreview={openSchedulerPreview}/></section><button type="button" className="refresh-button" onClick={()=>void refresh()}>Refresh status</button><WorkspaceShell/></>}
