"""Small, testable primitives for safe atomic Vault file mutations."""

from __future__ import annotations

import errno
import os
import secrets
from collections.abc import Callable
from pathlib import Path

from .errors import AlreadyExists, AtomicWriteError


def _fsync_directory(directory: Path) -> None:
    """Best-effort directory durability barrier on supported platforms."""
    flags = getattr(os, "O_RDONLY", 0) | getattr(os, "O_DIRECTORY", 0)
    fd: int | None = None
    try:
        fd = os.open(directory, flags)
        os.fsync(fd)
    except OSError as exc:
        # Windows and some virtual filesystems do not permit opening a
        # directory as an fsync target.  The file itself was already fsynced;
        # retain portability while surfacing other failures.
        if exc.errno not in {
            errno.EINVAL,
            errno.ENOTSUP,
            errno.EOPNOTSUPP,
            errno.EBADF,
            errno.EACCES,
        }:
            raise AtomicWriteError("Vault directory durability sync failed") from exc
    finally:
        if fd is not None:
            try:
                os.close(fd)
            except OSError:
                pass


def _new_temp_path(parent: Path) -> Path:
    # The random component is generated by the service, never accepted from a
    # request, and the O_EXCL open below closes the name-collision race.
    return parent / f".localnote-tmp-{os.getpid()}-{secrets.token_hex(12)}"


def _write_temp(parent: Path, data: bytes) -> Path:
    temp = _new_temp_path(parent)
    fd: int | None = None
    try:
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd = os.open(temp, flags, 0o600)
        with os.fdopen(fd, "wb", closefd=True) as stream:
            fd = None
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        return temp
    except OSError as exc:
        if fd is not None:
            try:
                os.close(fd)
            except OSError:
                pass
        try:
            temp.unlink(missing_ok=True)
        except OSError:
            pass
        raise AtomicWriteError("Unable to prepare the atomic Vault write") from exc


def atomic_write_bytes(
    target: Path,
    data: bytes,
    *,
    replace: bool,
    before_replace: Callable[[], None] | None = None,
    sync_parent: bool = True,
) -> None:
    """Write ``data`` via a same-directory fsynced temporary file.

    ``replace=True`` is used only for an already validated update and performs
    an atomic replacement.  ``replace=False`` uses an atomic hard-link create,
    so a concurrent existing target can never be silently overwritten.  The
    temporary file is removed on every failure.
    """
    parent = target.parent
    temp: Path | None = None
    try:
        temp = _write_temp(parent, data)
        if before_replace is not None:
            before_replace()

        if replace:
            # os.replace is atomic when source and target share a directory;
            # callers have already validated target and its parent.
            os.replace(temp, target)
            temp = None
        else:
            try:
                # link(2) creates the destination atomically and refuses an
                # existing target.  It also keeps the operation same-directory.
                os.link(temp, target, follow_symlinks=False)
            except FileExistsError as exc:
                raise AlreadyExists(path=None) from exc
            except OSError as exc:
                raise AtomicWriteError("Unable to create the Vault file atomically") from exc
            finally:
                try:
                    temp.unlink(missing_ok=True)
                except OSError:
                    pass
            temp = None

        if sync_parent:
            _fsync_directory(parent)
    except (AlreadyExists, AtomicWriteError):
        raise
    except OSError as exc:
        raise AtomicWriteError("Atomic Vault write failed") from exc
    finally:
        if temp is not None:
            try:
                temp.unlink(missing_ok=True)
            except OSError:
                pass


def atomic_create_bytes(target: Path, data: bytes, *, sync_parent: bool = True) -> None:
    """Convenience wrapper for a no-overwrite atomic create."""
    atomic_write_bytes(target, data, replace=False, sync_parent=sync_parent)


def atomic_replace_bytes(
    target: Path,
    data: bytes,
    *,
    before_replace: Callable[[], None] | None = None,
    sync_parent: bool = True,
) -> None:
    """Convenience wrapper for an atomic replacement."""
    atomic_write_bytes(
        target,
        data,
        replace=True,
        before_replace=before_replace,
        sync_parent=sync_parent,
    )


__all__ = ["atomic_create_bytes", "atomic_replace_bytes", "atomic_write_bytes"]
