//
//  AIProvider.swift
//  ReadFlow
//
//  The AI backend abstraction (contract §3).
//
//  Three backends, one protocol:
//    · `.localbook` — the existing `LocalBookClient.ask` path, a first-class
//      backend when the server is reachable;
//    · `.cloud`     — a user-configured OpenAI-compatible endpoint;
//    · `.offline`   — a *structured* degradation that needs no network at all.
//
//  The offline backend is deliberately not an error path. Per contract §6.2 the
//  degraded answer is a normal `AIResponse` with non-empty `text`, so callers
//  never have to distinguish "failed" from "answered offline"; the distinction
//  that *does* matter is carried by `provider` and `isDegraded`.
//

import Foundation

// MARK: - Capability kinds

/// Which backend produced an answer (contract §3.2, frozen).
enum AIProviderKind: String, Codable, CaseIterable {
    case localbook
    case cloud
    case offline
}

// MARK: - Request / response

/// One question, with the context needed to answer it.
///
/// `requestID` is generated by the caller and echoed back on the response so a
/// reply can always be paired with its request (contract §3.1).
struct AIRequest {
    let requestID: UUID
    let query: String
    let context: String
    let scope: AIScope
    let sourceID: UUID?
    let highlightID: UUID?
    let conversationID: UUID?

    init(
        requestID: UUID = UUID(),
        query: String,
        context: String = "",
        scope: AIScope = .currentContent,
        sourceID: UUID? = nil,
        highlightID: UUID? = nil,
        conversationID: UUID? = nil
    ) {
        self.requestID = requestID
        self.query = query
        self.context = context
        self.scope = scope
        self.sourceID = sourceID
        self.highlightID = highlightID
        self.conversationID = conversationID
    }
}

/// One answer, always structurally complete.
///
/// `text` is non-empty in **every** case, including offline: contract C17
/// forbids using an empty string to impersonate model output.
struct AIResponse {
    let requestID: UUID
    let text: String
    let citations: [AICitation]
    let provider: AIProviderKind
    /// `true` only when the answer is a degradation. `false` means "this is the
    /// requested backend answering normally" — including S1, where nothing was
    /// degraded because nothing was configured in the first place (§6.2).
    let isDegraded: Bool
    let model: String?
}

// MARK: - Errors

/// Failure classification (contract §3.5, frozen).
///
/// The cases are deliberately disjoint: `.timeout` must be distinguishable from
/// `.unreachable`, and both from `.unauthorized` / `.badResponse`, because the
/// fallback policy treats them differently (C5.2).
enum AIProviderError: Error, Equatable {
    /// endpoint or key missing.
    case notConfigured
    /// not `http`/`https`, or not parseable into a host.
    case invalidEndpoint(String)
    /// connection-level failure.
    case unreachable
    /// timed out.
    case timeout
    /// 401 / 403.
    case unauthorized
    /// 5xx, or an explicit server-side error (429 rate limiting lands here).
    case serverError(Int, String)
    /// 2xx but the body could not be understood.
    case badResponse
}

extension AIProviderError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .notConfigured:
            return "未配置云端 AI 服务"
        case .invalidEndpoint(let detail):
            return "Endpoint 无效：\(detail)"
        case .unreachable:
            return "无法连接云端服务"
        case .timeout:
            return "连接云端服务超时"
        case .unauthorized:
            return "云端鉴权失败（API Key 无效或已过期）"
        case .serverError(let status, let detail):
            return "AI 服务错误（HTTP \(status)）：\(detail)"
        case .badResponse:
            return "云端返回格式异常，无法解析响应"
        }
    }
}

// MARK: - Provider protocol

/// A backend capable of answering a question.
///
/// `ask` is `async throws` and must **never** signal failure with an optional
/// return value (contract §3.1): an unavailable provider either throws a typed
/// `AIProviderError` or returns a structured degradation.
protocol AIProvider: AnyObject {
    var kind: AIProviderKind { get }
    func ask(_ request: AIRequest) async throws -> AIResponse
    /// Cheap probe. Must not issue a paid completion request.
    func isAvailable() async -> Bool
}
