import type { WorkspacePreferences } from "./preferences";
import type { AIChatResponse, TrashEntryDTO, TrashListResponse, AIRelatedResponse, AISummarizeResponse, AITagsResponse, AttachmentUploadResponse, AttachmentUploadSource, BacklinkRef, FileReadResponse, FileMutationResponse, GraphQuery, GraphResponse, GraphScope, LinkRef, SearchResponse, VaultFileEntry, HistoryPageDTO, JobDetailDTO, UndoResponseDTO, JobCreateRequest, JobActionRequest } from "@localnote/protocol";
export type LoadState="idle"|"loading"|"ready"|"error"|"not_configured"|"unavailable";
export type SaveState="saved"|"saving"|"conflict"|"error";
export type EncodingState="utf8"|"invalid_utf8";
export type SearchState="idle"|"loading"|"ready"|"error";
export interface WorkspaceError {kind:"network"|"api"|"decode"|"preview"|"unknown";code?:string;status?:number;message:string;path?:string;meta?:{prompt_version?:string;model?:string};}
export interface ConflictInfo {code:"file_conflict";path:string;message:string;baseSha256:string;detectedAt:string;}
export interface EditorSession {path:string;content:string;baseSha256:string;baseContentBase64:string;byteLength:number;encoding:EncodingState;lineSeparator:"CRLF"|"LF"|"CR";hasBOM:boolean;dirty:boolean;saveState:SaveState;error:WorkspaceError|null;conflict:ConflictInfo|null;notice:string|null;requestVersion:number;}
export interface WorkspaceTab {path:string;title:string;dirty:boolean;loading:boolean;error:WorkspaceError|null;}
export interface FileTreeState {entries:VaultFileEntry[];expandedPaths:string[];collapsedPaths:string[];status:LoadState;error:WorkspaceError|null;}
/** The two path sets that decide whether one tree row shows its children. */
export interface FileTreeExpansion {expandedPaths:string[];collapsedPaths:string[];}
export interface NoteRelationsState {status:LoadState;path:string|null;outgoing:LinkRef[]|null;backlinks:BacklinkRef[]|null;brokenCount:number;error:WorkspaceError|null;}
export interface SearchStateBox {status:SearchState;query:string;response:SearchResponse|null;error:WorkspaceError|null;}
export type AIAction = "ask" | "summarize" | "tags" | "related" | "extract_todos" | "classify";
export interface AIStateBox {status: "idle" | "loading" | "ready" | "error" | "offline"; action: AIAction | null; notePath: string | null; response: AIChatResponse | AISummarizeResponse | AITagsResponse | AIRelatedResponse | import("@localnote/protocol").AIExtractTodosResponse | import("@localnote/protocol").AIClassifyResponse | null; error: WorkspaceError | null; requestVersion: number;}
export type AIWorkspaceResponse = AIChatResponse | AISummarizeResponse | AITagsResponse | AIRelatedResponse;
export type GraphStatus="idle"|"loading"|"ready"|"empty"|"error"|"unavailable";
export interface GraphStateBox {status:GraphStatus;scope:GraphScope;note:string|null;depth:number;direction:"both"|"outgoing"|"incoming";tag:string|null;includeBroken:boolean;limit:number;offset:number;response:GraphResponse|null;error:WorkspaceError|null;requestVersion:number;}
/**
 * Recycle bin view state. `retentionDays` is what the server promises, so the
 * UI never hard-codes "30 days" and stays correct if the window is configured.
 */
export interface TrashState {status:"idle"|"loading"|"ready"|"error";entries:TrashEntryDTO[];retentionDays:number;totalBytes:number;error:WorkspaceError|null;busy:boolean;}
export interface HistoryState {status: "idle" | "loading" | "ready" | "error"; page: HistoryPageDTO | null; selected: JobDetailDTO | null; error: WorkspaceError | null; requestVersion: number; busy: boolean; }
/** Attachment upload view state; never touches EditorSession save state. */
export interface AttachmentState {busy:boolean;error:WorkspaceError|null;lastPath:string|null;source:AttachmentUploadSource|null;}
export interface UploadAttachmentOptions {notePath?:string;targetDirectory?:string;source?:AttachmentUploadSource;}
/**
 * Options for the nested-document entry points. `name` is the default file
 * name without `.md` and is localised by the caller (the workspace package has
 * no i18n of its own), `content` seeds the new note's body, and
 * `linkFromOwner` (default `true`) adds a `[[wikilink]]` to the creating note
 * when that note is open and clean.
 */
export interface CreateChildNoteOptions {name?:string;content?:string;linkFromOwner?:boolean;}
/**
 * Bridge from the store to the mounted editor: inserts text at the live caret.
 * Returns false when that note has no editor mounted (store falls back to
 * appending at the end of the document).
 */
export type CaretInsertHandler = (path:string, markdown:string) => boolean;
export interface WorkspaceState extends WorkspacePreferences {workspaceFrozen:boolean;vaultStale:boolean;setPreferences:(value:Partial<WorkspacePreferences>)=>void;saveAll:()=>Promise<boolean>;resetVault:()=>void;tree:FileTreeState;tabs:WorkspaceTab[];activePath:string|null;sessions:Record<string,EditorSession>;relations:NoteRelationsState;search:SearchStateBox;graph:GraphStateBox;ai:AIStateBox;history:HistoryState;attachment:AttachmentState;trash:TrashState;theme:"light"|"dark";splitRatio:number;loadTree:()=>Promise<void>;toggleDirectory:(path:string)=>void;expandPath:(path:string)=>void;openFile:(path:string)=>Promise<void>;createNote:(path:string,content?:string)=>Promise<string>;createChildNote:(parentPath:string,options?:CreateChildNoteOptions)=>Promise<string>;createSiblingNote:(notePath:string,options?:CreateChildNoteOptions)=>Promise<string>;createFolder:(path:string)=>Promise<string>;moveEntry:(sourcePath:string,destinationDirectory:string)=>Promise<string>;deleteEntry:(path:string)=>Promise<string>;moveToTrash:(path:string)=>Promise<TrashEntryDTO|null>;loadTrash:()=>Promise<void>;restoreFromTrash:(entry:TrashEntryDTO)=>Promise<string|null>;deleteFromTrash:(entry:TrashEntryDTO)=>Promise<boolean>;emptyTrash:()=>Promise<boolean>;renameEntry:(path:string,newName:string)=>Promise<string>;ensureFolder:(directory:string)=>Promise<string>;openOrCreateLinkedNote:(fromPath:string|null|undefined,linkTarget:string)=>Promise<string>;toggleTask:(path:string,index:number)=>boolean;activateTab:(path:string)=>void;closeTab:(path:string,confirm?:()=>boolean)=>boolean;updateContent:(path:string,content:string)=>void;save:(path?:string,reason?:"auto"|"manual")=>Promise<void>;reloadConflict:(path:string)=>Promise<void>;keepLocal:(path:string)=>Promise<void>;loadRelations:(path:string)=>Promise<void>;clearRelations:()=>void;runSearch:(query:string)=>Promise<void>;clearSearch:()=>void;loadGraph:(overrides?:Partial<Pick<GraphStateBox,"scope"|"note"|"depth"|"direction"|"tag"|"includeBroken"|"limit"|"offset">>)=>Promise<void>;clearGraph:()=>void;runAI:(action:AIAction,args:any)=>Promise<void>;clearAI:()=>void;loadHistory:()=>Promise<void>;selectHistory:(id:string)=>Promise<void>;createJob:(request:JobCreateRequest)=>Promise<JobDetailDTO|null>;acceptJob:(id:string,request?:JobActionRequest)=>Promise<JobDetailDTO|null>;rejectJob:(id:string)=>Promise<JobDetailDTO|null>;undoHistory:(id:string)=>Promise<UndoResponseDTO|null>;setTheme:(theme:"light"|"dark")=>void;setSplitRatio:(ratio:number)=>void;uploadAndInsertAttachment:(file:File,options?:UploadAttachmentOptions)=>Promise<AttachmentUploadResponse|null>;insertMarkdownAtSelection:(path:string,markdown:string)=>boolean;registerCaretInsert:(handler:CaretInsertHandler|null)=>void;clearAttachmentError:()=>void;}
export type WorkspaceApi={fetchVaultFiles:(options?:{recursive?:boolean})=>Promise<{entries:VaultFileEntry[]}>;fetchVaultFile:(path:string)=>Promise<FileReadResponse>;patchVaultFile:(args:{path:string;contentBase64:string;expectedSha256:string})=>Promise<FileMutationResponse>;createVaultFile?:(args:{path:string;contentBase64:string})=>Promise<FileMutationResponse>;createVaultDirectory?:(args:{path:string})=>Promise<FileMutationResponse>;moveVaultFile?:(args:{sourcePath:string;destinationPath:string;expectedSha256?:string|null})=>Promise<FileMutationResponse>;deleteVaultFile?:(args:{path:string;expectedSha256:string})=>Promise<FileMutationResponse>;moveToTrash?:(args:{path:string;expectedSha256?:string|null})=>Promise<TrashEntryDTO>;fetchTrash?:()=>Promise<TrashListResponse>;restoreTrashEntry?:(args:{id:string;renameIfOccupied?:boolean})=>Promise<FileMutationResponse>;deleteTrashEntry?:(id:string)=>Promise<FileMutationResponse>;emptyTrash?:()=>Promise<FileMutationResponse|TrashListResponse>;fetchLinks?:(path:string)=>Promise<{outgoing:LinkRef[];broken_count:number}>;fetchBacklinks?:(path:string)=>Promise<{backlinks:BacklinkRef[]}>;searchNotes?:(query:string)=>Promise<SearchResponse>;fetchGraph?:(query?:GraphQuery)=>Promise<GraphResponse>;fetchLocalGraph?:(note:string,query?:GraphQuery)=>Promise<GraphResponse>;fetchTagGraph?:(tag:string,query?:GraphQuery)=>Promise<GraphResponse>;aiChat?:(args: import("@localnote/protocol").AIChatRequest)=>Promise<AIChatResponse>;aiSummarize?:(args: import("@localnote/protocol").AISummarizeRequest)=>Promise<AISummarizeResponse>;aiTags?:(args: import("@localnote/protocol").AITagsRequest)=>Promise<AITagsResponse>;aiRelated?:(args: import("@localnote/protocol").AIRelatedRequest)=>Promise<import("@localnote/protocol").AIRelatedResponse>;aiExtractTodos?:(args: import("@localnote/protocol").AIExtractTodosRequest)=>Promise<import("@localnote/protocol").AIExtractTodosResponse>;aiClassify?:(args: import("@localnote/protocol").AIClassifyRequest)=>Promise<import("@localnote/protocol").AIClassifyResponse>;listHistory?:()=>Promise<HistoryPageDTO>;getHistory?: (id:string)=>Promise<JobDetailDTO>;createJob?: (request:JobCreateRequest)=>Promise<JobDetailDTO>;acceptJob?: (id:string,request?:JobActionRequest)=>Promise<JobDetailDTO>;rejectJob?: (id:string)=>Promise<JobDetailDTO>;undoHistory?: (id:string)=>Promise<UndoResponseDTO>;uploadAttachmentBase64?:(args:{originalName:string;contentBase64:string;targetDirectory:string})=>Promise<AttachmentUploadResponse>;uploadAttachmentMultipart?:(file:File,targetDirectory:string,originalName?:string)=>Promise<AttachmentUploadResponse>;};
