import type { AIChatResponse, AIRelatedResponse, AISummarizeResponse, AITagsResponse, BacklinkRef, FileReadResponse, FileMutationResponse, GraphQuery, GraphResponse, GraphScope, LinkRef, SearchResponse, VaultFileEntry, HistoryPageDTO, JobDetailDTO, UndoResponseDTO, JobCreateRequest, JobActionRequest } from "@localnote/protocol";
export type LoadState="idle"|"loading"|"ready"|"error"|"not_configured"|"unavailable";
export type SaveState="saved"|"saving"|"conflict"|"error";
export type EncodingState="utf8"|"invalid_utf8";
export type SearchState="idle"|"loading"|"ready"|"error";
export interface WorkspaceError {kind:"network"|"api"|"decode"|"preview"|"unknown";code?:string;status?:number;message:string;path?:string;meta?:{prompt_version?:string;model?:string};}
export interface ConflictInfo {code:"file_conflict";path:string;message:string;baseSha256:string;detectedAt:string;}
export interface EditorSession {path:string;content:string;baseSha256:string;baseContentBase64:string;byteLength:number;encoding:EncodingState;dirty:boolean;saveState:SaveState;error:WorkspaceError|null;conflict:ConflictInfo|null;notice:string|null;requestVersion:number;}
export interface WorkspaceTab {path:string;title:string;dirty:boolean;loading:boolean;error:WorkspaceError|null;}
export interface FileTreeState {entries:VaultFileEntry[];expandedPaths:string[];status:LoadState;error:WorkspaceError|null;}
export interface NoteRelationsState {status:LoadState;path:string|null;outgoing:LinkRef[]|null;backlinks:BacklinkRef[]|null;brokenCount:number;error:WorkspaceError|null;}
export interface SearchStateBox {status:SearchState;query:string;response:SearchResponse|null;error:WorkspaceError|null;}
export type AIAction = "ask" | "summarize" | "tags" | "related" | "extract_todos" | "classify";
export interface AIStateBox {status: "idle" | "loading" | "ready" | "error" | "offline"; action: AIAction | null; notePath: string | null; response: AIChatResponse | AISummarizeResponse | AITagsResponse | AIRelatedResponse | import("@localnote/protocol").AIExtractTodosResponse | import("@localnote/protocol").AIClassifyResponse | null; error: WorkspaceError | null; requestVersion: number;}
export type AIWorkspaceResponse = AIChatResponse | AISummarizeResponse | AITagsResponse | AIRelatedResponse;
export type GraphStatus="idle"|"loading"|"ready"|"empty"|"error"|"unavailable";
export interface GraphStateBox {status:GraphStatus;scope:GraphScope;note:string|null;depth:number;direction:"both"|"outgoing"|"incoming";tag:string|null;includeBroken:boolean;limit:number;offset:number;response:GraphResponse|null;error:WorkspaceError|null;requestVersion:number;}
export interface HistoryState {status: "idle" | "loading" | "ready" | "error"; page: HistoryPageDTO | null; selected: JobDetailDTO | null; error: WorkspaceError | null; requestVersion: number; busy: boolean; }
export interface WorkspaceState {tree:FileTreeState;tabs:WorkspaceTab[];activePath:string|null;sessions:Record<string,EditorSession>;relations:NoteRelationsState;search:SearchStateBox;graph:GraphStateBox;ai:AIStateBox;history:HistoryState;theme:"light"|"dark";splitRatio:number;loadTree:()=>Promise<void>;toggleDirectory:(path:string)=>void;openFile:(path:string)=>Promise<void>;activateTab:(path:string)=>void;closeTab:(path:string,confirm?:()=>boolean)=>boolean;updateContent:(path:string,content:string)=>void;save:(path?:string,reason?:"auto"|"manual")=>Promise<void>;reloadConflict:(path:string)=>Promise<void>;keepLocal:(path:string)=>void;loadRelations:(path:string)=>Promise<void>;clearRelations:()=>void;runSearch:(query:string)=>Promise<void>;clearSearch:()=>void;loadGraph:(overrides?:Partial<Pick<GraphStateBox,"scope"|"note"|"depth"|"direction"|"tag"|"includeBroken"|"limit"|"offset">>)=>Promise<void>;clearGraph:()=>void;runAI:(action:AIAction,args:any)=>Promise<void>;clearAI:()=>void;loadHistory:()=>Promise<void>;selectHistory:(id:string)=>Promise<void>;createJob:(request:JobCreateRequest)=>Promise<JobDetailDTO|null>;acceptJob:(id:string,request?:JobActionRequest)=>Promise<JobDetailDTO|null>;rejectJob:(id:string)=>Promise<JobDetailDTO|null>;undoHistory:(id:string)=>Promise<UndoResponseDTO|null>;setTheme:(theme:"light"|"dark")=>void;setSplitRatio:(ratio:number)=>void;}
export type WorkspaceApi={fetchVaultFiles:(options?:{recursive?:boolean})=>Promise<{entries:VaultFileEntry[]}>;fetchVaultFile:(path:string)=>Promise<FileReadResponse>;patchVaultFile:(args:{path:string;contentBase64:string;expectedSha256:string})=>Promise<FileMutationResponse>;fetchLinks?:(path:string)=>Promise<{outgoing:LinkRef[];broken_count:number}>;fetchBacklinks?:(path:string)=>Promise<{backlinks:BacklinkRef[]}>;searchNotes?:(query:string)=>Promise<SearchResponse>;fetchGraph?:(query?:GraphQuery)=>Promise<GraphResponse>;fetchLocalGraph?:(note:string,query?:GraphQuery)=>Promise<GraphResponse>;fetchTagGraph?:(tag:string,query?:GraphQuery)=>Promise<GraphResponse>;aiChat?:(args: import("@localnote/protocol").AIChatRequest)=>Promise<AIChatResponse>;aiSummarize?:(args: import("@localnote/protocol").AISummarizeRequest)=>Promise<AISummarizeResponse>;aiTags?:(args: import("@localnote/protocol").AITagsRequest)=>Promise<AITagsResponse>;aiRelated?:(args: import("@localnote/protocol").AIRelatedRequest)=>Promise<import("@localnote/protocol").AIRelatedResponse>;aiExtractTodos?:(args: import("@localnote/protocol").AIExtractTodosRequest)=>Promise<import("@localnote/protocol").AIExtractTodosResponse>;aiClassify?:(args: import("@localnote/protocol").AIClassifyRequest)=>Promise<import("@localnote/protocol").AIClassifyResponse>;listHistory?:()=>Promise<HistoryPageDTO>;getHistory?: (id:string)=>Promise<JobDetailDTO>;createJob?: (request:JobCreateRequest)=>Promise<JobDetailDTO>;acceptJob?: (id:string,request?:JobActionRequest)=>Promise<JobDetailDTO>;rejectJob?: (id:string)=>Promise<JobDetailDTO>;undoHistory?: (id:string)=>Promise<UndoResponseDTO>;};
