"""Reader API request/response schemas."""

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field

# ============================================================================
# Enums
# ============================================================================


class DeviceType(StrEnum):
    """Device type enumeration."""

    MACOS = "macos"
    IOS = "ios"
    ANDROID = "android"


class SourceType(StrEnum):
    """Reader source type enumeration."""

    WEB = "web"
    PDF = "pdf"
    DOCUMENT = "document"
    MARKDOWN = "markdown"


class SyncOperation(StrEnum):
    """Sync operation type."""

    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"


class SyncEntityType(StrEnum):
    """Entity type for sync operations."""

    SOURCE = "source"
    SESSION = "session"
    HIGHLIGHT = "highlight"
    NOTE = "note"
    READER_ITEM = "reader_item"


# ============================================================================
# Device Pairing
# ============================================================================


class PairRequest(BaseModel):
    """Request to generate a pairing token."""

    device_name: str = Field(..., min_length=1, max_length=255)
    device_type: DeviceType


class PairResponse(BaseModel):
    """Response with pairing token."""

    pairing_token: str = Field(..., description="6-digit pairing code")
    expires_at: int = Field(..., description="Unix timestamp")


class RegisterRequest(BaseModel):
    """Request to register a device."""

    device_id: str = Field(..., description="UUIDv7 generated by client")
    device_name: str = Field(..., min_length=1, max_length=255)
    device_type: DeviceType
    pairing_token: str = Field(..., description="6-digit pairing code")
    public_key: str | None = Field(None, description="Optional device public key")


class RegisterResponse(BaseModel):
    """Response with access token."""

    access_token: str = Field(..., description="JWT token for API access")
    device_id: str


class DeviceStatusResponse(BaseModel):
    """Device status response."""

    device_id: str
    device_name: str
    device_type: DeviceType
    created_at: int
    last_seen: int
    is_active: bool


# ============================================================================
# Sync
# ============================================================================


class SyncOperationItem(BaseModel):
    """Single sync operation."""

    operation: SyncOperation
    entity_type: SyncEntityType
    entity_id: str = Field(..., description="UUIDv7")
    data: dict[str, Any] = Field(default_factory=dict)
    client_timestamp: int = Field(..., description="Unix timestamp from client")


class PushSyncRequest(BaseModel):
    """Batch push sync request."""

    operations: list[SyncOperationItem] = Field(..., min_length=1, max_length=100)


class SyncConflict(BaseModel):
    """Sync conflict information."""

    entity_type: SyncEntityType
    entity_id: str
    client_version: int | None = None
    server_version: int
    reason: str


class PushSyncResponse(BaseModel):
    """Batch push sync response.

    IDs are additive to the original count-based response. They let clients
    acknowledge only the operations the server actually accepted, without
    guessing from ordering when a batch contains a rejection or conflict.
    """

    accepted: int
    rejected: int
    accepted_ids: list[str] = Field(default_factory=list)
    rejected_ids: list[str] = Field(default_factory=list)
    conflicts: list[SyncConflict] = Field(default_factory=list)


class PullSyncRequest(BaseModel):
    """Pull sync request with cursor."""

    device_id: str
    cursor: str | None = Field(None, description="Last sync cursor, null for initial sync")
    limit: int = Field(100, ge=1, le=100)


class SyncEntity(BaseModel):
    """Synced entity data."""

    entity_type: SyncEntityType
    entity_id: str
    operation: SyncOperation
    data: dict[str, Any]
    timestamp: int


class PullSyncResponse(BaseModel):
    """Pull sync response with entities."""

    entities: list[SyncEntity]
    next_cursor: str | None = Field(None, description="Cursor for next batch, null if no more")
    has_more: bool


class CapabilitiesResponse(BaseModel):
    """Server capabilities response."""

    version: str = "1.0"
    max_batch_size: int = 100
    supported_source_types: list[SourceType] = Field(
        default_factory=lambda: [
            SourceType.WEB,
            SourceType.PDF,
            SourceType.DOCUMENT,
            SourceType.MARKDOWN,
        ]
    )
    features: dict[str, bool] = Field(
        default_factory=lambda: {
            "ai_chat": True,
            "semantic_search": True,
            "highlights": True,
            "notes": True,
            "conversations": True,
        }
    )


# ============================================================================
# AI Query
# ============================================================================


class AskRequest(BaseModel):
    """AI query request.

    The authenticated device is taken from the Bearer token by the router.
    ``device_id`` remains optional for compatibility with older Reader clients;
    the router never trusts it as the authentication identity.
    """

    device_id: str | None = None
    query: str = Field(..., min_length=1, max_length=4000)
    scope: Literal["current_content", "my_knowledge", "web"] = "current_content"
    conversation_id: str | None = Field(None, description="UUIDv7 for conversation context")
    source_id: str | None = Field(None, description="UUIDv7 for source context")
    highlight_id: str | None = Field(None, description="UUIDv7 for highlight context")
    context: str | None = Field(None, max_length=12000, description="Additional context text")


class Citation(BaseModel):
    """Citation reference."""

    source_id: str
    title: str | None = None
    url: str | None = None
    snippet: str | None = None


class AskResponse(BaseModel):
    """AI query response."""

    conversation_id: str
    message_id: str
    answer: str
    citations: list[Citation] = Field(default_factory=list)
    model: str | None = None


class SearchRequest(BaseModel):
    """Cross-Reader+LocalBook search request.

    Device identity comes from the authenticated Bearer token.  The optional
    field is retained only so older clients can continue sending it; the
    router overwrites it with the authenticated identity.
    """

    device_id: str | None = None
    query: str = Field(..., min_length=1)
    source_types: list[SourceType] | None = Field(None, description="Filter by source types")
    limit: int = Field(20, ge=1, le=100)


class SearchResult(BaseModel):
    """Single search result."""

    entity_type: str = Field(..., description="source | highlight | note | localnote")
    entity_id: str
    title: str | None = None
    snippet: str
    score: float
    url: str | None = None
    source_id: str | None = None


class SearchResponse(BaseModel):
    """Search response."""

    results: list[SearchResult]
    total: int
